version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: sinan
      MYSQL_DATABASE: ck_challenge
    ports:
      - "3307:3306"
    networks:
      - my_network
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    networks:
      - my_network

networks:
  my_network:
